In [11]:
#imports here

from bs4 import BeautifulSoup
from selenium import webdriver
import time
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

In [12]:
url = 'https://www.facebook.com'


s = Service("C:\\Users\\DELL\\chromedriver.exe")
driver = webdriver.Chrome(service=s)
driver.get(url)

email = driver.find_element(by=By.NAME,value="email")
pswrd = driver.find_element(by=By.NAME,value="pass")

driver.get('https://mbasic.facebook.com/profile')

pageContent = driver.page_source

soup = BeautifulSoup(pageContent, 'html.parser')

In [4]:
[0,1,0,1,0,1,1,1].count(1)

5

In [13]:
#program to parse user name who posted comment
def Nameparse():
    driver.get(url)
    names = driver.find_elements(by=By.TAG_NAME,value='h3')
    for name in names:
        name=name.text
        Name.append(name)

In [14]:
#program to parse comments
def Commentparse():
    driver.get(url)
    comments=driver.find_elements(by=By.CSS_SELECTOR,value="[class='eg']") or driver.find_elements(by=By.CSS_SELECTOR,value="[class='ee']") or driver.find_elements(by=By.CSS_SELECTOR,value="[class='ed']")
    for comment in comments:
        comment=comment.text
        Comment.append(comment)

In [15]:
#Program to scrap comments from each page
Name=[]
Comment=[]
cnt=0
#program to parse comments from 5 pages, if you want comments from all pages then use while loop
for i in range(1):
#while True:
    url=("https://mbasic.facebook.com/story.php?story_fbid=317380303920457&id=110703284588161&p=")
    url=url+str(cnt)
    Nameparse()
    print(Name)
    Commentparse()
    print(Comment)
    print(url)
    cnt=cnt+10  

['Rồng Thần Huyền Thoại', 'Nguyễn Gia Huy', 'Hoàn Phạm', 'Trần Nobii', 'Huỳnh Tô Hải Đăng', 'Phạm Hữu Nhơn', 'Trần Quang', 'Khoa Tominh', 'Huy Nguyễn', 'Nguyễn Thanh Hải', 'Hiển Nguyễn']
['Mong bulma lâu lâu hãy ra sự kiện web ạ chứ nhanh quá k có kc tiêu 🤣', 'Fc quà 50k mem bulma ơi', 'Khong có code fc ta', 'Fc', 'Thứ ae tôi cần là sk web 🤭', 'Fan cứng', 'Fc', 'Fc', 'fc', 'Hết cái chơi']
https://mbasic.facebook.com/story.php?story_fbid=317380303920457&id=110703284588161&p=0


In [16]:
driver.get("https://mbasic.facebook.com/minh.khoa.9216778?_rdr#_")
names = driver.find_elements(by=By.XPATH,value="// a[contains(text(),'Toàn bộ tin')]")
names[0].click()

In [8]:
print(str(driver.current_url))

https://mbasic.facebook.com/story.php?story_fbid=3173743902870995&id=100007062480379&refid=17&_ft_=mf_story_key.3173743902870995%3Atop_level_post_id.3173743902870995%3Atl_objid.3173743902870995%3Acontent_owner_id_new.100007062480379%3Aoriginal_content_id.302009508790870%3Aoriginal_content_owner_id.110703284588161%3Athrowback_story_fbid.3173743902870995%3Apage_id.110703284588161%3Astory_location.4%3Aattached_story_attachment_style.photo%3Aott.AX-9EuhEi8uGwQdA%3Aattached_story_type.EntStatusCreationStory%3Aattached_story_attachment_type.MediaAttachment%3Apage_insights.%7B%22110703284588161%22%3A%7B%22page_id%22%3A110703284588161%2C%22page_id_type%22%3A%22page%22%2C%22actor_id%22%3A100007062480379%2C%22attached_story%22%3A%7B%22page_id%22%3A110703284588161%2C%22page_id_type%22%3A%22page%22%2C%22actor_id%22%3A110703284588161%2C%22dm%22%3A%7B%22isShare%22%3A0%2C%22originalPostOwnerID%22%3A0%7D%2C%22psn%22%3A%22EntStatusCreationStory%22%2C%22post_context%22%3A%7B%22object_fbtype%22%3A266%2C%

In [9]:
text = driver.current_url

In [18]:
text.split("&")[0]+"&"+text.split("&")[1]

'https://mbasic.facebook.com/story.php?story_fbid=3173743902870995&id=100007062480379'

In [9]:

import pickle
from keras.models import load_model
model_ANN = load_model("Sentiment-ANN.h5")
model_KNN = pickle.load(open("Sentiment-knn.pickle", 'rb'))
model_BNB = pickle.load(open("Sentiment-BNB.pickle", 'rb'))
model_LR = pickle.load(open("Sentiment-LR.pickle", 'rb'))
model_RF = pickle.load(open("Sentiment-RandomF.pickle", 'rb'))
tranfrom = pickle.load(open("tranfrom_text.pkl", 'rb'))

c:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.1.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator BernoulliNB from version 1.1.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from versi

In [6]:
model = [model_ANN,model_KNN,model_BNB,model_LR,model_RF]

In [157]:
text = ['Hum nay chia tay lớp ,pùn wa', 'Tuần này thở k ra hơi .Đủ việc']
text = tranfrom.transform(text)
_model = model[1]
predict_status = _model.predict(text)

In [12]:
model_ANN_time = load_model("model_ann_time.h5")

In [18]:
import numpy as np
num=np.array([20,100])
model_ANN_time.predict(num.reshape(1,2))

array([[1.]], dtype=float32)

In [90]:
timess = [np.array([int(x),100]) for x in ['20', '18', '18', '21', '17', '17', '22', '21', '22', '19']]
timess = np.array(timess).reshape(len(timess),2)

In [91]:
predict_time = model_ANN_time.predict(timess)

In [158]:
text = [['U là tr', 'Ủaaaa'], [], ['Em cũng ngoan lắm á 👉🏻👈🏻'], [], ['Ố=)))'], ['Cầu nguyện cho con thi tốt đi là nó hông lỗ🤧'], ['Con mồn lèo này nguy hiểm lắm chú🥲'], ['Mai nấu'], ['Hay quá chị yêu'], []]
while(text.__contains__([])):
    text.remove([])
predict_comment = [_model.predict(tranfrom.transform(x)) for x in text]

In [161]:
np.array(predict_comment)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [160]:
for idx in range(len(predict_comment)):
    if(len(predict_comment[idx])>1):
        if(np.array(predict_comment[idx]).tolist().count(1) > np.array(predict_comment[idx]).tolist().count(0)): 
            predict_comment[idx] = [1]
        else:
            predict_comment[idx] = [0]

In [162]:
[int(x) for x in np.array(predict_comment)]

[1, 1, 1, 1, 1, 1, 1]

In [128]:
predict_comment

[[[0.0]],
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64)]

In [129]:
[int(x) for x in np.array(predict_comment)]

C:\Users\DELL\AppData\Local\Temp\ipykernel_1048\3619942791.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  [int(x) for x in np.array(predict_comment)]


TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [81]:
[int(x) for x in np.array(predict_time).reshape(-1)].count(1)

2